name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: docker-compose build

      - name: Run containers
        run: docker-compose up -d

      - name: Wait and Test
        run: |
          sleep 15
          curl http://localhost:5000
